import { HttpStatus } from "@nestjs/common";

export const ErrorMessageMap: Record<HttpStatus, string> = {
    [HttpStatus.OK]: 'Success',
    [HttpStatus.BAD_REQUEST]: 'Bad request',
    [HttpStatus.UNAUTHORIZED]: 'Unauthorized',
    [HttpStatus.FORBIDDEN]: 'Forbidden',
    [HttpStatus.NOT_FOUND]: 'Not found',
    [HttpStatus.INTERNAL_SERVER_ERROR]: 'Internal server error',
    [HttpStatus.CONTINUE]: "",
    [HttpStatus.SWITCHING_PROTOCOLS]: "",
    [HttpStatus.PROCESSING]: "",
    [HttpStatus.EARLYHINTS]: "",
    [HttpStatus.CREATED]: "",
    [HttpStatus.ACCEPTED]: "",
    [HttpStatus.NON_AUTHORITATIVE_INFORMATION]: "",
    [HttpStatus.NO_CONTENT]: "",
    [HttpStatus.RESET_CONTENT]: "",
    [HttpStatus.PARTIAL_CONTENT]: "",
    [HttpStatus.AMBIGUOUS]: "",
    [HttpStatus.MOVED_PERMANENTLY]: "",
    [HttpStatus.FOUND]: "",
    [HttpStatus.SEE_OTHER]: "",
    [HttpStatus.NOT_MODIFIED]: "",
    [HttpStatus.TEMPORARY_REDIRECT]: "",
    [HttpStatus.PERMANENT_REDIRECT]: "",
    [HttpStatus.PAYMENT_REQUIRED]: "",
    [HttpStatus.METHOD_NOT_ALLOWED]: "",
    [HttpStatus.NOT_ACCEPTABLE]: "",
    [HttpStatus.PROXY_AUTHENTICATION_REQUIRED]: "",
    [HttpStatus.REQUEST_TIMEOUT]: "",
    [HttpStatus.CONFLICT]: "",
    [HttpStatus.GONE]: "",
    [HttpStatus.LENGTH_REQUIRED]: "",
    [HttpStatus.PRECONDITION_FAILED]: "",
    [HttpStatus.PAYLOAD_TOO_LARGE]: "",
    [HttpStatus.URI_TOO_LONG]: "",
    [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: "",
    [HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE]: "",
    [HttpStatus.EXPECTATION_FAILED]: "",
    [HttpStatus.I_AM_A_TEAPOT]: "",
    [HttpStatus.MISDIRECTED]: "",
    [HttpStatus.UNPROCESSABLE_ENTITY]: "",
    [HttpStatus.FAILED_DEPENDENCY]: "",
    [HttpStatus.PRECONDITION_REQUIRED]: "",
    [HttpStatus.TOO_MANY_REQUESTS]: "",
    [HttpStatus.NOT_IMPLEMENTED]: "",
    [HttpStatus.BAD_GATEWAY]: "",
    [HttpStatus.SERVICE_UNAVAILABLE]: "",
    [HttpStatus.GATEWAY_TIMEOUT]: "",
    [HttpStatus.HTTP_VERSION_NOT_SUPPORTED]: ""
};